name: Send Foodie.earth Menu

# Controls when the action will run
on:
  # Runs at 16:00 UTC (9:00 AM PDT / 8:00 AM PST) every Sunday and Wednesday
  schedule:
    - cron: '0 16 * * 0,3' # 0=Sunday, 3=Wednesday
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape-and-post:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed
    steps:
      # 1. Checks-out your repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Sets up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installs Python packages
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # 4. Runs your main Python script
      - name: Run Scraper and Post to Discord
        env:
          # Make the secret available as an environment variable
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python3 send_menu.py
